# Generated by Django 6.0.5 on 2026-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mii', models.CharField(max_length=20)),
                ('idade_mii', models.IntegerField(default='?')),
                ('datadenascimento_mii', models.DateField()),
                ('comidasfavoritas_mii1', models.TextField()),
                ('comidasfavoritas_mii2', models.TextField()),
                ('personalidade_mii', models.TextField()),
                ('generomii', models.TextField()),
                ('generoquegostamii', models.TextField()),
            ],
        ),
    ]
