# Generated by Django 6.0.5 on 2026-06-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_comida', models.CharField()),
                ('nome_comida', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ilha', models.CharField()),
                ('proprietario_ilha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Mii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mii', models.CharField(max_length=20)),
                ('idade_mii', models.PositiveIntegerField(blank=True, null=True)),
                ('datadenascimento_mii', models.DateField(blank=True, null=True)),
                ('personalidade_mii', models.CharField(choices=[('0', 'Achiever'), ('1', 'Maverick'), ('2', 'Rogue'), ('3', 'Visionary'), ('4', 'Buddy'), ('5', 'Cheerleader'), ('6', 'Daydreamer'), ('7', 'Sweetie'), ('8', 'Charmer'), ('9', 'Dynamo'), ('10', 'Go-Getter'), ('11', 'Merrymaker'), ('12', 'Observer'), ('13', 'Perfectionist'), ('14', 'Thinker'), ('15', 'Strategist')])),
                ('genero_mii', models.CharField(choices=[('0', 'Masculine'), ('1', 'Feminine'), ('2', 'Non-binary')])),
                ('generoquegosta_mii', models.CharField(blank=True, choices=[('0', 'Hetero'), ('1', 'Homo'), ('2', 'Bi')], null=True)),
                ('felicidade_mii', models.IntegerField(default=0)),
                ('ilha_mii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miis.ilha')),
            ],
        ),
    ]
