# Generated by Django 6.0.5 on 2026-06-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mii',
            name='comidasfavorita1_mii',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miis.comida'),
        ),
    ]
