# Generated by Django 6.0.5 on 2026-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mii',
            name='generomii',
            field=models.TextField(choices=[('Feminine', 'Feminine')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generoquegostamii',
            field=models.TextField(blank=True, choices=[('Homo', 'Homo')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='personalidade_mii',
            field=models.TextField(choices=[('Maverick', 'Maverick'), ('(Individualist)', '(Individualist)')]),
        ),
    ]
