# Generated by Django 6.0.5 on 2026-06-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0002_mii_comidasfavorita1_mii'),
    ]

    operations = [
        migrations.AddField(
            model_name='mii',
            name='comidasfavorita2_mii',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorita2_mii', to='miis.comida'),
        ),
        migrations.AlterField(
            model_name='mii',
            name='comidasfavorita1_mii',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorita1_mii', to='miis.comida'),
        ),
    ]
