# Generated by Django 6.0.5 on 2026-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0002_alter_mii_generomii_alter_mii_generoquegostamii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mii',
            name='comidasfavoritas_mii1',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mii',
            name='comidasfavoritas_mii2',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generomii',
            field=models.CharField(choices=[('Feminine', 'Feminine')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generoquegostamii',
            field=models.CharField(blank=True, choices=[('Homo', 'Homo')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='personalidade_mii',
            field=models.CharField(choices=[('Maverick', 'Maverick'), ('(Individualist)', '(Individualist)')]),
        ),
    ]
