# Generated by Django 6.0.5 on 2026-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0003_alter_mii_comidasfavoritas_mii1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mii',
            name='generomii',
            field=models.CharField(choices=[(1, 'Masculine'), (2, 'Feminine'), (3, 'Non-binary')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generoquegostamii',
            field=models.CharField(blank=True, choices=[(1, 'Hetero'), (2, 'Homo'), (3, 'Bi')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='personalidade_mii',
            field=models.CharField(choices=[(1, 'Achiever (Busy Bee)'), (2, 'Maverick (Individualist)'), (3, 'Rogue (Individualist)'), (4, 'Visionary (Leader)'), (5, 'Buddy (Carer)'), (6, 'Cheerleader (Optimist)'), (7, 'Daydreamer (Dreamer)'), (8, 'Sweetie (Softie)'), (9, 'Charmer'), (10, 'Dynamo (Hot-Blooded)'), (11, 'Go-Getter (Adventurer)'), (12, 'Merrymaker (Bubbly)'), (13, 'Observer (Introvert)'), (14, 'Perfectionist'), (15, 'Thinker'), (16, 'Strategist (Patient)')]),
        ),
    ]
