# Generated by Django 6.0.5 on 2026-06-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0003_mii_comidasfavorita2_mii_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mii',
            old_name='comidasfavorita1_mii',
            new_name='comidafavorita1_mii',
        ),
        migrations.RenameField(
            model_name='mii',
            old_name='comidasfavorita2_mii',
            new_name='comidafavorita2_mii',
        ),
    ]
