# Generated by Django 6.0.5 on 2026-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0004_rename_comidasfavorita1_mii_mii_comidafavorita1_mii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mii',
            name='comidafavorita2_mii',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mii',
            name='comidafavorita1_mii',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mii',
            name='genero_mii',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não-binário', 'Não-binário')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generoquegosta_mii',
            field=models.CharField(blank=True, choices=[('Hetero', 'Hetero'), ('Homo', 'Homo'), ('Bi', 'Bi')], null=True),
        ),
        migrations.AlterField(
            model_name='mii',
            name='personalidade_mii',
            field=models.CharField(choices=[('Achiever', 'Achiever'), ('Maverick', 'Maverick'), ('Rogue', 'Rogue'), ('Visionary', 'Visionary'), ('Buddy', 'Buddy'), ('Cheerleader', 'Daydreamer'), ('Sweetie', 'Sweetie'), ('Charmer', 'Charmer'), ('Dynamo', 'Dynamo'), ('Go-Getter', 'Go-Getter'), ('Merrymaker', 'Merrymaker'), ('Observer', 'Observer'), ('Perfectionist', 'Perfectionist'), ('Thinker', 'Thinker'), ('Strategist', 'Strategist')]),
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
