# Generated by Django 6.0.5 on 2026-06-19 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('miis', '0005_alter_mii_comidafavorita2_mii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilha',
            name='proprietario_ilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil'),
        ),
    ]
