# Generated by Django 6.0.5 on 2026-05-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0005_alter_mii_comidasfavoritas_mii1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField()),
                ('categoria_item', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ilha', models.CharField()),
                ('proprietario_ilha', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obs', models.CharField()),
                ('horario_obs', models.TimeField()),
                ('data_obs', models.DateField()),
                ('descricao_obs', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='mii',
            name='felicidade_mii',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generomii',
            field=models.CharField(choices=[('0', 'Masculine'), ('1', 'Feminine'), ('2', 'Non-binary')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='generoquegostamii',
            field=models.CharField(blank=True, choices=[('0', 'Hetero'), ('1', 'Homo'), ('2', 'Bi')]),
        ),
        migrations.AlterField(
            model_name='mii',
            name='personalidade_mii',
            field=models.CharField(choices=[('0', 'Achiever'), ('1', 'Maverick'), ('2', 'Rogue'), ('3', 'Visionary'), ('4', 'Buddy'), ('5', 'Cheerleader'), ('6', 'Daydreamer'), ('7', 'Sweetie'), ('8', 'Charmer'), ('9', 'Dynamo'), ('10', 'Go-Getter'), ('11', 'Merrymaker'), ('12', 'Observer'), ('13', 'Perfectionist'), ('14', 'Thinker'), ('15', 'Strategist')]),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miis.item')),
                ('sabor_comida', models.CharField()),
            ],
            bases=('miis.item',),
        ),
    ]
