# Generated by Django 6.0.5 on 2026-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0006_item_ilha_observacao_mii_felicidade_mii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mii',
            name='felicidade_mii',
            field=models.IntegerField(),
        ),
    ]
