# Generated by Django 6.0.5 on 2026-06-20 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0006_alter_ilha_proprietario_ilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilha',
            name='data_criacao_ilha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
