# Generated by Django 6.0.6 on 2026-06-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('miis', '0007_alter_mii_felicidade_mii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Observacao',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='comidasfavoritas_mii1',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='comidasfavoritas_mii2',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='datadenascimento_mii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='felicidade_mii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='generomii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='generoquegostamii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='idade_mii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='nome_mii',
        ),
        migrations.RemoveField(
            model_name='mii',
            name='personalidade_mii',
        ),
        migrations.AddField(
            model_name='comida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='comida',
            name='nome_comida',
            field=models.CharField(default='NAOTEM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilha',
            name='proprietario_ilha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.perfil'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
