# Generated by Django 6.0.5 on 2026-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0007_ilha_data_criacao_ilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mii',
            name='foto_mii',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_miis/'),
        ),
        migrations.AlterField(
            model_name='ilha',
            name='data_criacao_ilha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
