# Generated by Django 6.0.6 on 2026-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0008_remove_comida_item_ptr_delete_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
