# Generated by Django 6.0.5 on 2026-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0008_mii_foto_mii_alter_ilha_data_criacao_ilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mii',
            name='detalhes_mii',
            field=models.CharField(blank=True, null=True),
        ),
    ]
