# Generated by Django 6.0.6 on 2026-06-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0009_alter_comida_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comida',
            old_name='id',
            new_name='id_comida',
        ),
    ]
