# Generated by Django 6.0.5 on 2026-06-20 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0009_mii_detalhes_mii'),
    ]

    operations = [
        migrations.AddField(
            model_name='mii',
            name='data_criacao_mii',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
