# Generated by Django 6.0.6 on 2026-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miis', '0010_rename_id_comida_id_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='id_comida',
        ),
        migrations.AddField(
            model_name='comida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
